NOTE: Presentation rate is about 100 words / minute. For 20 minutes then, 2000 words.

* Introduction (8 minutes) 1:45

- Lenard

- [SLIDE] The synthesis of integral dimensions

- [SLIDE] Even the simplest of lab-based stimuli have multiple varying attributes. 

- Monochromatic squares are presented at different sizes and brightnesses.

- Pure sine waves are presented at different pitches and intensities

- How do we process these multiple attributes in order to classify the objects in our world?

- [SLIDE] There are two, approximately opposite, classes of theory: Differentiation Theory and Combination Theory

- [SLIDE] Differentiation Theory says that stimuli are initially perceived as undifferentiated wholes or 'blobs'. In this slide, I represent a grey square being perceived as an unanalyzed blob, by placing it inside this purple blob

- So, under Differentiation Theory, stimuli are initially perceived as undifferentiated blobs. But, with time and effort people can analyze the stimulus into its constituent dimensions

- [SLIDE] It's worth noting that much of psychology appears to assume some form of Differentiation Theory.

- We can see this in the widespread use of the terms 'analytic' and 'nonanalytic' - or 'holistic' -  to describe modes of thought. 

- For example, it is often stated that WEIRD populations differ from other cultures in the unusual extent to which their thought is analytic rather than holistic.

- Such a description presupposes a form of Differentiation Theory.

- [SLIDE] Starting with Fraser's Ph.D. work, and through to work most recently reported last year, our lab has, I think, built a strong case that Differentiation Theory is wrong -- at least for the stimuli and procedures we have studied. 

- Instead, all the work we have done in this period points in the opposite direction, to a class of theory we describe as Combination Theory.

- The idea is as old as Cognitive Psychology - literally. You'll find it in Neisser's book of that name. 

- [SLIDE] Combination Theory argues that cognition begins with the stimulus attributes... 

-  ...and that these attributes are combined if time and mental resources allow. 

- [SLIDE] This theory correctly predicts the effects of time pressure, cognitive load, and incidental training on the classification of a variety of stimuli across a range of procedures.

- Basically, this research shows that the less time or mental resources we have to apply to a classification, the fewer stimulus attributes we use.

- [SLIDE] In the current set of experiments, we deliberately tried to break Combination Theory.

- In all previous work supportive of Combination Theory, the stimuli are what is described as 'separable'. 

- This term comes from a converging set of operational definitions of separable versus integral stimuli, proposed by Garner in the 1970s.

- They have been a matter of broad consensus since that time.

- Perhaps the easiest way to think about the difference between separable and integral stimuli is in terms of the ease with which people can attend to one stimulus attribute while ignoring the other.

- So, for example, if we are asked to classify a set of rectangles on their brightness, ignoring their size, this is easy to do.

- This stimulus set is therefore separable.

- Other stimulus sets, however, are integral. For these it is hard to classify on the basis of one attribute while ignoring the other.

- For example, it is difficult to classify square of red hue on the basis of their brightness, ignoring their saturation. 

- This stimulus set is therefore integral.

- Our question was this. For integral stimuli, which is the more appropriate class of theory? Combination Theory, as for integral stimuli? Or Differentiation Theory?

- There seems to be a case for Differentiation Theory for these stimuli. 

- The fact that we struggle to attend to one stimulus attribute while ignoring the other might be taken to imply the presence of a 'holisitic blob' representation of these stimuli, which is split into its components only with some effort. 

- Indeed, analysis of the historical record indicates the the existence of integral stimuli was a major motivator in the development of Differentiation Theory. 

- Differentiation Theory, then, would argue that integral stimuli are difficult to analyze.

- What does Combination Theory predict?

- Combination Theory still has to predict that the stimulus attributes - for example brightness and saturation - are combined over time. 

- Under Combination Theory, the difficulty of selective attention for integral stimuli comes from the fact that integral stimuli are _quickly synthesized_. 

- In other words, the brightness and saturation attributes are rapidly combined.

- Once combined, it requires effort to selectively attend to just one of them ...

- ...this assumption is already part of Combination Theory and has been used to explain previous results.

- How do we distinguish the predictions of Combination and Differentiation Theory for integral stimuli?

- [SLIDE] Actually, it's pretty straight forward, because they make opposite predictions about the effects of time pressure on classification.

- Combination Theory predicts that, with sufficiently high time pressure, participants will classify integral stimuli on the basis of a single attribute (e.g. brightness) because the attributes have not yet been combined. 

- With less time pressure, the attributes will have been combined, and the classification will be on the basis of overall similarity. 

- Differentiation Theory makes the opposite prediction. 

- To the extent time pressure has any effect at all, Differentiation Theory predicts that classification on the basis of a single attribute will be more likely as time pressure reduces. 

- So, that's what we set out to test. What is the effect of time pressure on the classification of integral stimuli?

* Method (5 minutes) 1:53

- [SLIDE] So, by now, our independent variable should be obvious - time pressure. Stimuli were either presented for 100 ms and 2000 ms. Time to respond was not limited, but limiting stimulus presentation time is known to exert significant time pressure on participants. 

- The choice of stimuli is fairly straight forward, too. We need integral stimuli, and red hue squares varying in saturation and brightness are the set of stimuli most extensively confirmed as being integral in nature.

- What about the procedure?

- Well, one paradigmatic classification task when it comes to the integral/separable distinction is the 'triad' classification task - also known as the 'restricted classification' task.

- [SLIDE] In this task, the participant is presented with three stimuli...

- [SLIDE] ... and asked to pick the odd one out.

- There are no 'right' answers, and no feedback is given.

- [SLIDE] On every trial, the three stimuli presented have the following relationship to each other

- [SLIDE] These two stimuli are identical on one dimension but very different on the other. 

- [SLIDE] These two stimuli are similar on both dimensions, but identical on neither.

- On each trial, the dimension containing the identity is randomly selected by the experimenter.

- So, on some trials, the two stimuli are identical in brightness. In others they are identical in saturation.

- [SLIDE] In this experiment, we used a total of eight stimuli, from which eight stimulus triads can be formed.

- There are also six different ways in which three stimuli can be placed in three spatial locations, so that gives us 48 distinct stimulus triads.

- Participants were shown each twice, in a random order. 

- So, there was a total of 96 trials, which were presented in blocks of eight trials.

- [SLIDE] On each trial, there are basically three things people could be doing

- They could classify on the basis of overall similarity. This is what people do with integral stimuli in the absence of time pressure.

- They could classify  on the basis of identity, putting the two stimuli with the identical attribute together, ignoring the large difference on the other dimension. This is what people tend to do with separable stimuli in the absence of time pressure.

- They could classify on the basis of a single dimension. For example, they could classify on the basis of brightness, ignoring saturation.

- It's not possible to work out what they're doing on the basis of a single trial, because for any given trial, more than one strategy leads to the same behaviour. 

- For example, in triad 1-3-7, classifying on the basis of overall similarity leads to the same response as classifying on the basis of brightness alone.

- However, across the 96 trials of the experiment, we calculate how many trials are predicted by each of the three strategies - single-dimension, overall similarity, and identity.

- The strategy that accounts for the most responses is considered to be the strategy employed by that participant.

- We have used this analysis technique successfully in the past on the triad task, for example in Wills et al. (2015).

* Results #1 (2 min) 1:58
- [SLIDE] So, what did we find? 

- This table shows the number of participants using a single-dimension ("UD"), overall similarity, or Identity strategy, in each condition. "Bias" indicates one person pressed the same key all the time. 

- So, what does these results tell us. Basically ... bugger!

- As expected, everyone in the low time pressure condition classified on the basis of overall similarity.

- However, this was also close to being the case for the high time pressure condition.

- This null result can be accommodated by either account - Combination Theory or Differentiation Theory. For example, under Combination Theory, perhaps the time pressure was not sufficiently great to show an effect.

- So, we did a further, exploratory analysis

- Rather than looking at an individual's responses 'in one lump' i.e. across all 96 trials of the experiment, we looked at their performance on each of the eight-trial blocks.

- We speculated that this analysis might be more sensitive to low levels of single-dimensional classification assuming that, due to both internal and external noise, participants sometimes successfully classified on the basis of both dimensions but other times did not have time to combine both dimensions and hence responded on the basis of a single dimension.

- Although this form of analysis has not been used before in the triad task, it's the standard analysis for the match-to-standard task, which we've used in our lab for about 20 years now.

- [SLIDE] That worked. The proportion of blocks classified on the basis of a single dimension was higher in the 100 ms than in the 2000 ms condition. 

- This is the result predicted by Combination Theory.

- It disconfirms Differentiation Theory.

* Result #2 (1 min) 2:00

- Now ... an uncharitable soul might jump in at this point to point out that what we've done here might be a form of 'p hacking'. 

- We did our planned analysis. It didn't support our theory. So we tried another analysis. That one worked, and that's the one we believe. Are we fooling ourslves?

- The obvious way to check this is to directly replicate the experiment, so that's what we did.

- We ran the experiment again, planning to do this by-block analysis from the outset.

- [SLIDE] It worked, again. 

- Very compellingly.

- Time pressure increased single-dimension responding. Combination Theory is right. Differentiation Theory is wrong. 

* Result #3 (2 min) 2:01

- So far, we've assumed that people perceive our stimuli in the manner described by their physical stimulus attributes - brightness, saturation.

- In a third and final experiment, we checked the validity of that assumption.

- We did this by asking a separate group of people to rate every possible pair of our eight stimuli for similarity on a 1-9 scale. 

- From this information, we can use multidimensional scaling to infer the psychological stimulus space for these stimuli. 

- [SLIDE] And here's what we found. On the left is the physical stimulus space. On the right is the psychological stimulus space as determined by multidimensional scaling. 

- For most stimuli, the correspondence between the physical and psychological space was pretty good.

- For stimuli 2 and 4, they seem to have been perceived as somewhat brighter and more saturated than their physical description would indicate.

- This might have been as a result of us using commodity hardware for stimulus display.

- Do these moderate deviations of psychological space from physical space cast doubt on our conclusions?

- No. 

- In a final analysis, we use the psychological stimulus co-ordinates to re-analyze the data of the two previous experiments, combined into a single data set.

- [SLIDE] As you can see, using the psychological representation of these stimuli increased the magnitude of the effect. In fact, it more of less doubled in size. 

- Bayesian analysis provides strong evidence for our conclusion. However you rated the relative likelihood of the experimental and null hypotheses before these data, Bayesian analysis indicates you should increase that ratio in favour of the experimental hypothesis by a factor of approximately nine hundread.

* Discussion (2 min) 2:03
...And that's about it. 

- [SLIDE] Combination Theory wins, Differentiation Theory loses.

- Combination Theory already provided a superior explanation of the effects of time pressure, concurrent load, and incidental training for separable stimuli, across a range of procedures.

- We've now shown, that Combination Theory also works better than Differentiation Theory for integral stimuli. To be honest, this was not really the result we were expecting -- we thought Combination Theory would break for these sorts of stimuli.

- So… stimuli, then, are not a blob that is 'analyzed' into its components if we have time.

- Rather, the components come first, and we combine those components if we have time.

- It would seem then, that "analysis" is a poor chemical metaphor for the mental processes underlying classification. 

- [SLIDE] Our cognitive chemist do not analyse mysterious compounds. They synthesize stimulus compounds from their components.

- There may be wider implications here for the ways we think about modes of thought. Perhaps, rather than thinking in terms of analytic and non-analytic (or holistic) modes of thought, we should think about the extend to which thought is synthetic or non-synthetic.

- Thank you! I'm happy to take questions :-)

* End 2:05
* Links
https://www.news24.com/w24/Work/Jobs/meet-south-africas-most-successful-black-women-in-science-20180821

